<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/', 'Home::index');
// Chat endpoint (AJAX/CORS safe) put early for priority
$routes->match(['GET','POST','OPTIONS'], 'chat', 'Chat::index');
$routes->match(['GET','POST','OPTIONS'], 'index.php/chat', 'Chat::index');
$routes->resource('posts', ['controller' => 'Post']);

service('auth')->routes($routes);

// Auto-generated by Scaffold command on 2025-06-19 18:36:00
$routes->resource('blogposts', ['controller' => 'BlogPostController']);

// Auto-generated by Scaffold command on 2025-06-19 19:08:09
$routes->resource('acustomers', ['controller' => 'ACustomerController']);

$routes->match(['GET','POST'],'builder', 'Builder::index');
