<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/', 'Home::index');
$routes->resource('posts', ['controller' => 'Post']);

service('auth')->routes($routes);

// Auto-generated by Scaffold command on 2025-06-19 18:36:00
$routes->resource('blogposts', ['controller' => 'BlogPostController']);

// Auto-generated by Scaffold command on 2025-06-19 19:08:09
$routes->resource('acustomers', ['controller' => 'ACustomerController']);

$routes->match(['get','post'],'builder', 'Builder::index');

$routes->post('chat', 'Chat::index');
